name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: expr
      id: expr
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: expr
        setup-command: mvn package
        command: java -cp "chocopy-ref.jar:target/assignment.jar" chocopy.ChocoPy
          --pass=s --test --dir src/test/data/pa1/sample/expr_plus.py
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EXPR_RESULTS: "${{steps.expr.outputs.result}}"
      with:
        runners: expr
