name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: expr_plus
      id: expr_plus
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: expr_plus
        setup-command: ''
        command: java -cp "chocopy-ref.jar:target/assignment.jar" chocopy.ChocoPy
          --pass=s --test --dir src/test/data/pa1/sample/expr_plus.py
        input: ''
        expected-output: 'Tests: 1 passed, 0 failed, and 0 ignored.'
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EXPR_PLUS_RESULTS: "${{steps.expr_plus.outputs.result}}"
      with:
        runners: expr_plus
